### ISSUE TITLE
Can you share the Caffe model or tell me how to get it?

### ISSUE THREAD

**Issue by Dawson-huang** [elliottd/satyrid#4]
VGG_MODEL = '/home/delliott/src/caffe/models/vgg_19/VGG_ILSVRC_19_layers.caffemodel'
VGG_DEPLOY = '/home/delliott/src/caffe/models/vgg_19/VGG_ILSVRC_19_layers_deploy.prototxt'

Thank you very much!

**Comment by elliottd** [comment]
Sorry I missed this question.

The Caffe model is downloaded from the [Oxford VGG website](http://www.robots.ox.ac.uk/~vgg/research/very_deep/).

**Comment by Dawson-huang** [comment]
Thank you for your answer. I get it！
